version: '3'

services:
  mbpfan:
    privileged: true
    image: mbpfan:latest
    build: .
    container_name: mbpfan
    hostname: mbpfan
    restart: unless-stopped
    volumes:
      - ./etc/mbpfan.conf:/etc/mbpfan.conf